name: build

on:
  push:
    branches:
      - master

  # Run tests for any PRs.
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 13.x, 14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm install
      - name: npm build
        run: npm run build
      - name: Pine test
        run: npm run pine:prod test
        env:
          CI: true
